on:
  push:
    branches:
      - alpha

name: alpha-build

jobs:
  assets:
    name: Create NPM Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          always-auth: true

      - name: List current directory
        run : ls -la

      - name: Get package version
        uses: nyaascii/package-version@v1

      - name: Show env
        run: |
        echo "my version ${{ env.PACKAGE_VERSION }}"
        echo "show env ${{ env }}"

      - name: Bump alpha version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.1
        with:
          current-version: '${{ env.PACKAGE_VERSION }}'
          version-fragment: 'alpha'
      - name: Do something with your bumped release version
        run: echo ${{ steps.bump_version.outputs.next-version }}

      #- name: Get actual versions from npm
      #  id: get-versions
      #  run: yarn info
      #- name: Increase version
      #  run: |
      #    git config --global user.name "drite"
      #    git config --global user.email "gubarevfyodor@gmail.com"
      #    yarn version --preid=alpha
      #- name: install
      #  run: yarn install
      #- name: linter
      #  run: yarn lint
      #- name: build
      #  run: yarn build
      #- name: Publish dist to NPM
      #  run: |
      #    echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      #    cd dist
      #    yarn publish --tag alpha --access public
      #    cd ..
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
