# This is a basic workflow to help you get started with Actions

name: build-alpha-from-pr

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-alpha:
    name: Build alpha package
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/alpha')
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get package version
        uses: nyaascii/package-version@v1

      - name: Show env
        run: |
          echo "Package version ${{ env.PACKAGE_VERSION }}"

      - name: Grep version fron NPM registry
        run: |
          yarn info @drite/tesler-ui-core 'dist-tags' | grep -Eo "${{ env.PACKAGE_VERSION }}"

