name: Run doc tests

on:
  issue_comment:
    types: [ created ]

jobs:
  send-message:
    name: Send message
    environment: doc
    env:
      token: ${{ secrets.EVENT_DISPATCH_TOKEN }}
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/testDoc')
    runs-on: ubuntu-latest
    steps:
      - name: Get info
        run: |
          echo '${{ github.GITHUB_REF }}'
          echo '${{ github.GITHUB_SHA }}'
#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.EVENT_DISPATCH_TOKEN }}
#          repository: DRITE/tesler-doc
#          event-type: test_doc
